# wrangler.toml

# A name for your project configuration (can be anything descriptive)
name = "health-equity-viewer"

# Use a recent compatibility date
compatibility_date = "2025-4-10" # Or a newer date suggested by Wrangler

# --- Cloudflare Pages Configuration ---

# Tells `wrangler pages dev` where your static site files are located.
pages_build_output_dir = "."

# --- Bindings for Local Development (`wrangler pages dev`) ---
# These tell the local dev server what cloud resources your Function needs.
# You MUST also configure these in the Cloudflare Dashboard for deployment.

[[r2_buckets]]
# This variable name MUST match how you access it in your code (env.GEOJSON_BUCKET)
binding = "GEOJSON_BUCKET"
# This is the EXACT name of the R2 bucket you created in Cloudflare.
# Using a separate "-preview" bucket for local dev is recommended but optional.
bucket_name = "se-mi-health-equity-data-myuan"

